version: 0.0
os: linux

files:
  - source: /geostore.war
    destination: /var/lib/tomcat/webapps

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: clear_server.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: unzipfile.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: start_server.sh
      timeout: 200
      runas: ec2-user
  ApplicationStop:
    - location: stop_server.sh
      timeout: 200
      runas: ec2-user
  # file_exists_behavior: OVERWRITE    