version: 0.0
os: linux

files:
  - source: /geostore.war
    destination: /opt/tomcat/webapps/

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: clear_server.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: start_server.sh
      timeout: 200
      runas: ubuntu
  ApplicationStop:
    - location: stop_server.sh
      timeout: 200
      runas: ubuntu
  file_exists_behavior: OVERWRITE    