version:  0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "installing Java version 11"
  pre_build:
    commands:
      - echo "entering build stage running"
  build:
    commands:
      - cd src/
      - mvn clean install -DskipTests
  post_build:
    commands:
     - echo "build complete"
artifacts:
  files:
    - src/web/app/target/*.war
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes